insert into directors (id, first_name, last_name) values (1, 'Caddric', 'Lorroway');
insert into directors (id, first_name, last_name) values (2, 'Brittne', 'Geeritz');
insert into directors (id, first_name, last_name) values (3, 'Eloise', 'Negus');
insert into directors (id, first_name, last_name) values (4, 'Dwight', 'Lacy');
insert into directors (id, first_name, last_name) values (5, 'Alley', 'Chater');
insert into directors (id, first_name, last_name) values (6, 'Joel', 'St Quenin');
insert into directors (id, first_name, last_name) values (7, 'Ruth', 'Letten');
insert into directors (id, first_name, last_name) values (8, 'Tristam', 'Resdale');
insert into directors (id, first_name, last_name) values (9, 'Arabelle', 'Ure');
insert into directors (id, first_name, last_name) values (10, 'Tarrance', 'Abrahmson');

insert into movies (id, title, date, director_id) values (1, 'Perfect World, A', '2021-09-01', 1);
insert into movies (id, title, date, director_id) values (2, 'Che: Part Two', '2021-07-04', 1);
insert into movies (id, title, date, director_id) values (3, 'Seeking Justice', '2021-06-15', 1);
insert into movies (id, title, date, director_id) values (4, 'The Coven', '2022-07-03', 1);
insert into movies (id, title, date, director_id) values (5, 'Carnal Knowledge', '2021-11-01', 1);
insert into movies (id, title, date, director_id) values (6, 'Phantom of the Opera, The', '2022-03-02', 1);
insert into movies (id, title, date, director_id) values (7, 'Immortel (ad vitam) (Immortal)', '2021-06-04', 1);
insert into movies (id, title, date, director_id) values (8, 'As Cool As I Am', '2021-11-03', 1);
insert into movies (id, title, date, director_id) values (9, 'Venice/Venice', '2021-05-08', 1);
insert into movies (id, title, date, director_id) values (10, 'Booty Call', '2022-07-03', 1);
insert into movies (id, title, date, director_id) values (11, 'Melissa P.', '2021-10-01', 1);
insert into movies (id, title, date, director_id) values (12, 'Poultrygeist: Night of the Chicken Dead', '2021-10-27', 1);
insert into movies (id, title, date, director_id) values (13, 'Israeli Intelligence (Hamosad Hasagur)', '2022-07-23', 1);
insert into movies (id, title, date, director_id) values (14, 'This Must Be the Place', '2021-10-30', 1);
insert into movies (id, title, date, director_id) values (15, 'Burglars, The (Le casse)', '2021-03-05', 1);
insert into movies (id, title, date, director_id) values (16, 'The Lego Movie', '2021-07-01', 1);
insert into movies (id, title, date, director_id) values (17, 'Where the Red Fern Grows', '2021-09-26', 1);
insert into movies (id, title, date, director_id) values (18, 'Touchy Feely', '2021-05-03', 1);
insert into movies (id, title, date, director_id) values (19, 'Mortdecai', '2021-06-19', 1);
insert into movies (id, title, date, director_id) values (20, 'Mark Shoots First', '2022-12-26', 1);
insert into movies (id, title, date, director_id) values (21, 'Juche Idea, The', '2021-04-07', 1);
insert into movies (id, title, date, director_id) values (22, 'How to Cook Your Life', '2021-09-01', 1);
insert into movies (id, title, date, director_id) values (23, 'Whip and the Body, The (Frusta e il corpo, La)', '2021-08-12', 1);
insert into movies (id, title, date, director_id) values (24, 'Capture of Bigfoot, The', '2022-07-23', 1);
insert into movies (id, title, date, director_id) values (25, 'Departures (Okuribito)', '2021-11-01', 1);
insert into movies (id, title, date, director_id) values (26, 'Method to the Madness of Jerry Lewis', '2022-07-12', 1);
insert into movies (id, title, date, director_id) values (27, 'Kirikou and the Sorceress (Kirikou et la sorcière)', '2022-11-01', 1);
insert into movies (id, title, date, director_id) values (28, 'To the Sea (Alamar)', '2022-11-10', 1);
insert into movies (id, title, date, director_id) values (29, 'Ernest Saves Christmas', '2021-09-18', 1);
insert into movies (id, title, date, director_id) values (30, 'Sebastian Maniscalco: What''s Wrong with People?', '2022-06-01', 1);
insert into movies (id, title, date, director_id) values (31, 'Four Christmases', '2021-07-11', 1);
insert into movies (id, title, date, director_id) values (32, 'Pekka ja Pätkä Suezilla', '2022-09-16', 1);
insert into movies (id, title, date, director_id) values (33, 'Boys Town', '2021-09-26', 1);
insert into movies (id, title, date, director_id) values (34, 'All Relative', '2021-01-18', 1);
insert into movies (id, title, date, director_id) values (35, 'The Green Years', '2021-04-05', 1);
insert into movies (id, title, date, director_id) values (36, 'Blue Juice', '2021-12-11', 1);
insert into movies (id, title, date, director_id) values (37, 'Bollywood/Hollywood', '2021-01-08', 1);
insert into movies (id, title, date, director_id) values (38, 'American Mary', '2022-09-08', 1);
insert into movies (id, title, date, director_id) values (39, 'Brain Donors', '2022-02-23', 1);
insert into movies (id, title, date, director_id) values (40, 'Don Quixote', '2022-03-30', 1);
insert into movies (id, title, date, director_id) values (41, 'The Missionaries', '2021-04-17', 1);
insert into movies (id, title, date, director_id) values (42, 'Matter of Life and Death, A (Stairway to Heaven)', '2021-10-27', 1);
insert into movies (id, title, date, director_id) values (43, 'American Pie', '2021-07-13', 1);
insert into movies (id, title, date, director_id) values (44, 'Blondes at Work', '2022-03-08', 1);
insert into movies (id, title, date, director_id) values (45, 'Brief Crossing (Brève traversée)', '2022-09-15', 1);
insert into movies (id, title, date, director_id) values (46, 'Ass Backwards', '2021-07-03', 1);
insert into movies (id, title, date, director_id) values (47, 'Last Time I Committed Suicide, The', '2022-09-20', 1);
insert into movies (id, title, date, director_id) values (48, 'Thirty Day Princess', '2022-02-20', 1);
insert into movies (id, title, date, director_id) values (49, 'Home on the Range', '2022-10-06', 1);
insert into movies (id, title, date, director_id) values (50, 'Where Are the Dreams of Youth? (Seishun no yume imaizuko)', '2022-02-12', 1);
insert into movies (id, title, date, director_id) values (51, 'Blackout', '2022-02-10', 1);
insert into movies (id, title, date, director_id) values (52, 'The Perfect World of Kai', '2022-05-23', 1);
insert into movies (id, title, date, director_id) values (53, 'Electric Dreams', '2022-04-18', 1);
insert into movies (id, title, date, director_id) values (54, 'Mississippi Mermaid (Sirène du Mississipi, La)', '2022-09-25', 1);
insert into movies (id, title, date, director_id) values (55, 'Art of War, The', '2022-06-21', 1);
insert into movies (id, title, date, director_id) values (56, 'Brainstorm', '2021-12-10', 1);
insert into movies (id, title, date, director_id) values (57, 'Housebound', '2021-02-03', 1);
insert into movies (id, title, date, director_id) values (58, 'Tree of Life, The', '2021-02-01', 1);
insert into movies (id, title, date, director_id) values (59, 'Meet the Robinsons', '2021-12-26', 1);
insert into movies (id, title, date, director_id) values (60, 'Three Wishes', '2022-07-15', 1);
insert into movies (id, title, date, director_id) values (61, 'Once Upon a Time in China III (Wong Fei-hung tsi sam: Siwong tsangba)', '2022-12-25', 1);
insert into movies (id, title, date, director_id) values (62, 'So Much So Fast', '2022-10-16', 1);
insert into movies (id, title, date, director_id) values (63, 'Wrestler, The (Painija)', '2022-12-07', 1);
insert into movies (id, title, date, director_id) values (64, 'Assassination Games', '2022-01-23', 1);
insert into movies (id, title, date, director_id) values (65, 'All the King''s Men', '2022-05-18', 1);
insert into movies (id, title, date, director_id) values (66, 'Masks (Masques)', '2022-06-21', 1);
insert into movies (id, title, date, director_id) values (67, 'Modify ', '2022-05-14', 1);
insert into movies (id, title, date, director_id) values (68, 'Wrecked', '2022-01-13', 1);
insert into movies (id, title, date, director_id) values (69, 'State of Siege (État de siège)', '2021-12-28', 1);
insert into movies (id, title, date, director_id) values (70, 'Time to Live, a Time to Die, A (Tong nien wang shi)', '2022-02-06', 1);
insert into movies (id, title, date, director_id) values (71, 'Timbuktu', '2021-12-03', 1);
insert into movies (id, title, date, director_id) values (72, 'Game Plan, The', '2021-08-19', 1);
insert into movies (id, title, date, director_id) values (73, 'Crooked Arrows', '2022-10-22', 1);
insert into movies (id, title, date, director_id) values (74, 'Cinderella II: Dreams Come True', '2021-04-09', 1);
insert into movies (id, title, date, director_id) values (75, 'Stella Does Tricks', '2021-08-27', 1);
insert into movies (id, title, date, director_id) values (76, 'Living Wake, The', '2022-01-28', 1);
insert into movies (id, title, date, director_id) values (77, 'Monster X Strikes Back: Attack the G8 Summit, The (Girara no gyakushû: Tôya-ko Samitto kikiippatsu)', '2022-11-12', 1);
insert into movies (id, title, date, director_id) values (78, 'Palookaville', '2022-07-02', 1);
insert into movies (id, title, date, director_id) values (79, 'This Land Is Mine', '2022-08-09', 1);
insert into movies (id, title, date, director_id) values (80, 'Day of the Falcon', '2022-07-17', 1);
insert into movies (id, title, date, director_id) values (81, 'Blitz', '2022-04-14', 1);
insert into movies (id, title, date, director_id) values (82, 'Orphans of the Storm', '2021-04-10', 1);
insert into movies (id, title, date, director_id) values (83, 'Fantastic Four: Rise of the Silver Surfer', '2021-10-14', 1);
insert into movies (id, title, date, director_id) values (84, 'Bats', '2022-07-28', 1);
insert into movies (id, title, date, director_id) values (85, 'All Together, The', '2022-07-30', 1);
insert into movies (id, title, date, director_id) values (86, 'Killing Room, The', '2021-12-02', 1);
insert into movies (id, title, date, director_id) values (87, 'Deserter (Dezertir)', '2021-01-10', 1);
insert into movies (id, title, date, director_id) values (88, 'Ocean''s Thirteen', '2021-09-18', 1);
insert into movies (id, title, date, director_id) values (89, 'Revenge of the Nerds', '2022-12-10', 1);
insert into movies (id, title, date, director_id) values (90, 'Taken', '2021-04-15', 1);
insert into movies (id, title, date, director_id) values (91, 'Life as We Know It', '2021-07-23', 1);
insert into movies (id, title, date, director_id) values (92, 'Tom and Jerry: The Movie', '2022-10-03', 1);
insert into movies (id, title, date, director_id) values (93, 'Grande école', '2021-12-19', 1);
insert into movies (id, title, date, director_id) values (94, 'Monster House', '2021-09-03', 1);
insert into movies (id, title, date, director_id) values (95, 'Austenland', '2022-01-23', 1);
insert into movies (id, title, date, director_id) values (96, 'Guard, The', '2021-02-05', 1);
insert into movies (id, title, date, director_id) values (97, 'Svensson, Svensson - I nöd och lust', '2022-11-02', 1);
insert into movies (id, title, date, director_id) values (98, 'Spitfire Grill, The', '2022-07-08', 1);
insert into movies (id, title, date, director_id) values (99, 'Laughing Woman, The (Frightened Woman, The) (Femina ridens)', '2022-10-26', 1);
insert into movies (id, title, date, director_id) values (100, 'How About You...', '2022-02-18', 1);

update movies set director_id = floor(1 + rand() * 9);